name: Publish docs to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx
        pip install numpydoc
    - name: Install numpy-financial
      run: |
        pip install .
    - name: Build documentation with Sphinx
      run: |
        cd doc
        make html
    - name: Update gh-pages
      run: |
        mv build/html /tmp
        git checkout gh-pages
        git rm -r *
        git commit -m "Remove old documentation"
        cp -r /tmp/html .
        touch .nojekyll
        git add -A
        git commit -m "Add new documentation"
        git push origin gh-pages
