name: Publish docs to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -q -y install dvipng texlive-latex-extra
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx
        pip install numpydoc
    - name: Install numpy-financial
      run: |
        pip install .
    - name: Build documentation with Sphinx
      run: |
        cd doc
        make html
        mv build/html /tmp
        cd ..
    - name: Push the new documentation to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #git remote rm origin
        #git remote add origin "https://${GITHUB_TOKEN}@github.com/numpy/numpy-financial.git"
        git config user.email "github.workflow@nomail"
        git config user.name "Github Workflow: publish_docs_to_pages.yml"
        echo "Fetching gh-pages"
        git fetch "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/numpy/numpy-financial.git" gh-pages
        echo "Checking out gh-pages branch"
        git checkout gh-pages
        echo "Removing old documentation"
        git clean -xdf .
        git rm -r '*'
        echo "Committing empty repository"
        git commit -m "Remove old documentation"
        echo "Copying /tmp/html here"
        cp -v -r /tmp/html/* .
        touch .nojekyll
        echo "Adding new documentation"
        git add -A
        git commit -m "Add new documentation"
        echo "Pushing new documentation to origin"
        git push -v "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/numpy/numpy-financial.git" gh-pages
